server:
  port: 8081
  servlet-path: /ntpclient

app:
  config:
    #pool.ntp.org
    #ntp-server-address: pool.ntp.org
    # 东华
    #ntp-server-address: 192.168.0.82
    # 麦科田
    #ntp-server-address: 192.168.0.58
    # 融昕
    #ntp-server-address: 192.168.0.136
#    ntp-server-address: 192.168.0.37
    ntp-server-address: 127.0.0.1
    # ntp123端口
    ntp-server-port: 123
    timeZonePort: 1234
    ntp-version: 4
    ntp-timeout: 3000
    charset-linux: UTF-8
    charset-windows: GBK
    cmd-timeout: 5000
